# Generated by Django 5.0.6 on 2024-07-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tonkho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensp', models.CharField(max_length=30)),
                ('masanpham', models.CharField(max_length=30)),
                ('gia_ban', models.IntegerField()),
                ('solo', models.IntegerField()),
                ('makho', models.CharField(max_length=30)),
                ('masp', models.CharField(max_length=30)),
                ('Tennsx', models.CharField(max_length=30)),
                ('tennhom', models.CharField(max_length=30)),
                ('tenkho', models.CharField(max_length=30)),
                ('ngayhethangsudung', models.DateField(auto_now_add=True)),
                ('soluongxuat', models.IntegerField(default=0)),
                ('soluongnhap', models.IntegerField(default=0)),
                ('tondauky', models.IntegerField(default=0)),
                ('soluongton', models.IntegerField(default=0)),
                ('soluongtontaithoidiem', models.IntegerField(default=0)),
                ('tonthucte', models.IntegerField(default=0)),
                ('thanhtien', models.IntegerField(default=0)),
            ],
        ),
    ]
