# Generated by Django 5.0.6 on 2024-07-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonkho', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tonkho',
        ),
    ]
