# Generated by Django 5.0.6 on 2024-07-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tonkho', '0002_delete_tonkho'),
    ]

    operations = [
        migrations.CreateModel(
            name='tonkhotongs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('masp', models.IntegerField(max_length=11)),
                ('solo', models.CharField(max_length=50)),
                ('soluongxuat', models.IntegerField(max_length=100)),
                ('soluongnhap', models.IntegerField(max_length=100)),
                ('ngaynhapxuat', models.DateTimeField()),
                ('handung', models.DateField()),
                ('makho', models.IntegerField(max_length=11)),
                ('maTC', models.IntegerField(max_length=11)),
            ],
        ),
    ]
