# Generated by Django 5.0.6 on 2024-07-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonkho', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonkhotongs',
            name='maTC',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tonkhotongs',
            name='makho',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tonkhotongs',
            name='masp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tonkhotongs',
            name='soluongnhap',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tonkhotongs',
            name='soluongxuat',
            field=models.IntegerField(),
        ),
    ]
