# Generated by Django 5.0.6 on 2024-07-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonkho', '0004_alter_tonkhotongs_matc_alter_tonkhotongs_makho_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tonkhotongs',
        ),
    ]
