# Generated by Django 5.0.3 on 2024-08-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_kh', models.CharField(max_length=50, unique=True)),
                ('ten', models.CharField(max_length=130)),
                ('dia_chi_nha_rieng', models.CharField(blank=True, max_length=90, null=True)),
                ('dien_thoai', models.CharField(max_length=100)),
                ('dc', models.CharField(max_length=220)),
                ('ten_huyen', models.CharField(max_length=90)),
                ('ten_tinh', models.CharField(max_length=90)),
                ('ten_nhom_kh', models.CharField(max_length=100)),
                ('ten_nhan_vien', models.CharField(max_length=120)),
                ('mota', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateField()),
            ],
        ),
    ]
