# Generated by Django 5.0.3 on 2024-08-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khachhang', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
