# Generated by Django 5.0.3 on 2024-08-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('Masanpham', models.AutoField(primary_key=True, serialize=False)),
                ('tensp', models.CharField(max_length=250)),
                ('Mansx', models.IntegerField()),
                ('gia_ban', models.CharField(max_length=100)),
                ('gia_nhap', models.CharField(max_length=100)),
                ('chietkhau', models.CharField(max_length=100)),
                ('Giakm', models.CharField(max_length=100)),
                ('Url', models.CharField(max_length=100)),
                ('Mota', models.CharField(max_length=1000)),
                ('Linksp', models.CharField(max_length=100)),
                ('Manhom', models.CharField(max_length=100)),
                ('Madonvi', models.IntegerField()),
                ('xx', models.CharField(max_length=300)),
                ('MaSP', models.CharField(max_length=100)),
                ('loaisp', models.IntegerField()),
                ('maTC', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sản Phẩm',
                'verbose_name_plural': 'Các Sản Phẩm',
                'db_table': 'sanphams',
            },
        ),
    ]
