# Generated by Django 5.0.3 on 2024-09-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SanPham',
        ),
    ]
