# Generated by Django 5.0.3 on 2024-08-19 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChucVu',
            fields=[
                ('maCV', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenCV', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chucvus',
            },
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('maPB', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenPB', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'phongbans',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('maNV', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenNV', models.CharField(max_length=100)),
                ('diaChi', models.CharField(max_length=255)),
                ('gioiTinh', models.CharField(max_length=10)),
                ('ngaySinh', models.DateField()),
                ('danToc', models.CharField(max_length=50)),
                ('sdt', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('honNhan', models.CharField(max_length=50)),
                ('soCMT', models.CharField(max_length=20)),
                ('noiCap', models.CharField(max_length=100)),
                ('tonGiao', models.CharField(max_length=50)),
                ('quocTich', models.CharField(max_length=50)),
                ('loaiNV', models.CharField(max_length=50)),
                ('nguoiTao', models.CharField(max_length=100)),
                ('maTC', models.CharField(max_length=10)),
                ('maCV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhanvien.chucvu')),
                ('maPB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhanvien.phongban')),
            ],
            options={
                'db_table': 'nhanvien',
            },
        ),
    ]
