# Generated by Django 5.0.3 on 2024-08-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='maCV',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='maPB',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ChucVu',
        ),
        migrations.DeleteModel(
            name='PhongBan',
        ),
    ]
