# Generated by Django 5.0.3 on 2024-08-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0002_alter_nhanvien_macv_alter_nhanvien_mapb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhanvien',
            old_name='ngaySinh',
            new_name='Ngaysinh',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='danToc',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='diaChi',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='email',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='honNhan',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='loaiNV',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='maCV',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='nguoiTao',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='noiCap',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='quocTich',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='sdt',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='tonGiao',
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='Manhomnd',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='Matkhau',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='anhNV',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='gioiTinh',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='maNV',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='maPB',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='maTC',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='soCMT',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='tenNV',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='nhanvien',
            table='nhanviens',
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='Dantoc',
            field=models.TextField(default='Kinh'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='Diachi',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='Email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='Honnhan',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='loainv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='MaCV',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='nguoitao',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='Noicap',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='Quoctich',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='Sdt',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='Tongiao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
