# Generated by Django 5.0.3 on 2024-08-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0003_rename_ngaysinh_nhanvien_ngaysinh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='Dantoc',
            field=models.TextField(),
        ),
    ]
