# Generated by Django 5.0.3 on 2024-08-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0004_alter_nhanvien_dantoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NhanVien',
        ),
    ]
